// flow-typed signature: 769c73a1e8b1b1a93158770f2db63568
// flow-typed version: <<STUB>>/d3-request_v^1.0.6/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-request/build/d3-request' {
  declare module.exports: any;
}

declare module 'd3-request/build/d3-request.min' {
  declare module.exports: any;
}

declare module 'd3-request/build/d3-request.node' {
  declare module.exports: any;
}

declare module 'd3-request/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-request/src/csv' {
  declare module.exports: any;
}

declare module 'd3-request/src/dsv' {
  declare module.exports: any;
}

declare module 'd3-request/src/html' {
  declare module.exports: any;
}

declare module 'd3-request/src/json' {
  declare module.exports: any;
}

declare module 'd3-request/src/request' {
  declare module.exports: any;
}

declare module 'd3-request/src/text' {
  declare module.exports: any;
}

declare module 'd3-request/src/tsv' {
  declare module.exports: any;
}

declare module 'd3-request/src/type' {
  declare module.exports: any;
}

declare module 'd3-request/src/xml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-request/build/d3-request.js' {
  declare module.exports: $Exports<'d3-request/build/d3-request'>;
}
declare module 'd3-request/build/d3-request.min.js' {
  declare module.exports: $Exports<'d3-request/build/d3-request.min'>;
}
declare module 'd3-request/build/d3-request.node.js' {
  declare module.exports: $Exports<'d3-request/build/d3-request.node'>;
}
declare module 'd3-request/index' {
  declare module.exports: $Exports<'d3-request'>;
}
declare module 'd3-request/index.js' {
  declare module.exports: $Exports<'d3-request'>;
}
declare module 'd3-request/rollup.config.js' {
  declare module.exports: $Exports<'d3-request/rollup.config'>;
}
declare module 'd3-request/src/csv.js' {
  declare module.exports: $Exports<'d3-request/src/csv'>;
}
declare module 'd3-request/src/dsv.js' {
  declare module.exports: $Exports<'d3-request/src/dsv'>;
}
declare module 'd3-request/src/html.js' {
  declare module.exports: $Exports<'d3-request/src/html'>;
}
declare module 'd3-request/src/json.js' {
  declare module.exports: $Exports<'d3-request/src/json'>;
}
declare module 'd3-request/src/request.js' {
  declare module.exports: $Exports<'d3-request/src/request'>;
}
declare module 'd3-request/src/text.js' {
  declare module.exports: $Exports<'d3-request/src/text'>;
}
declare module 'd3-request/src/tsv.js' {
  declare module.exports: $Exports<'d3-request/src/tsv'>;
}
declare module 'd3-request/src/type.js' {
  declare module.exports: $Exports<'d3-request/src/type'>;
}
declare module 'd3-request/src/xml.js' {
  declare module.exports: $Exports<'d3-request/src/xml'>;
}
